baseURL = "http://celix.apache.org"
title = "Apache Celix"
languageCode = "en"

contentDir = "source"
publishDir = "target/content"

disablePathToLower = true
uglyURLs = true
enableRobotsTXT = true
disableBrowserError = true
timeout = 3000

disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = [ ] # No files to ignore

# Highlighting config. See https://help.farbox.com/pygments.html
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

[blackfriday]
hrefTargetBlank = true
fractions = false

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[params]
repositoryUrl = "https://github.com/apache/celix"
repositorySourceBranch = "develop"

siteRepositoryUrl = "https://github.com/apache/celix-site"
siteRepositorySourceBranch = "master"
