baseURL = "https://celix.apache.org"
title = "Apache Celix"
languageCode = "en"

contentDir = "source"
publishDir = "target/content"

disablePathToLower = true
uglyURLs = true
enableRobotsTXT = true
disableBrowserError = true
timeout = 3000

disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = [ ] # No files to ignore

# Highlighting config. See https://help.farbox.com/pygments.html
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

[markup.goldmark.renderer]
unsafe= true

[blackfriday]
# hrefTargetBlank = true # We don't want everything opened in a new window
fractions = false

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[params]
latestVersion = "2.3.0"

repositoryUrl = "https://github.com/apache/celix"
repositorySourceBranch = "master"

siteRepositoryUrl = "https://github.com/apache/celix-site"
siteRepositorySourceBranch = "master"
